const CompanyList = [
  { name: "Cognizant" },
  { name: "Amdocs" },
  { name: "Dassault" },
  { name: "IdealCrew" },
  { name: "TCS" },
  { name: "Wipro" },
  { name: "Mindtree" },
  { name: "Accenture" },
  { name: "Deloitte" },
  { name: "IBM" },
  { name: "HCL" },
  { name: "Infosys" },
  { name: "Emtec" },
  { name: "HSBC" },
  { name: "Syntel" },
  { name: "Tech Mahindra" },
  { name: "ZenSer" },
];
export default CompanyList;
